server:
  port: 8787
spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      indent_output: true
  security:
    user:
      name: admin
      password: admin
logging:
  config: classpath:logback-spring.xml
