spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_cloud_uac?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  security:
    user:
      name: user
      password: root